# Generated by Django 5.1.1 on 2024-10-20 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('idFood', models.AutoField(primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=255)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('carbohydrates', models.FloatField(blank=True, null=True)),
                ('fats', models.FloatField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('idMeal', models.AutoField(primary_key=True, serialize=False)),
                ('nameMeal', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('idDiary', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('water_intake', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diary')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.meal')),
            ],
        ),
        migrations.AddField(
            model_name='diary',
            name='meals',
            field=models.ManyToManyField(through='diary.DiaryMeal', to='diary.meal'),
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.meal')),
            ],
        ),
    ]
