# Generated by Django 5.1.1 on 2024-10-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.CharField(blank=True, choices=[('sedentario', 'Sedentario'), ('ligera', 'Ligero'), ('moderada', 'Moderado'), ('activo', 'Activo'), ('muy_activo', 'Muy activo')], max_length=20, null=True, verbose_name='Actividad Fisica'),
        ),
    ]
