# Generated by Django 5.1.1 on 2024-10-22 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_diet_calories_alter_diet_carbohydrates_and_more'),
        ('users', '0003_user_iddiet_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idDiet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='nutrition.diet'),
        ),
    ]
