# Generated by Django 5.1.1 on 2024-10-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calories',
            field=models.FloatField(blank=True, null=True, verbose_name='Calorias'),
        ),
    ]
