# Generated by Django 5.1.1 on 2024-10-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_iddiet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='idDiet',
        ),
    ]
