# Generated by Django 5.1.1 on 2024-10-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_iddiet'),
        ('users', '0005_user_calories'),
    ]

    operations = [
    ]
