# Generated by Django 5.1.1 on 2024-10-18 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulas',
            fields=[
                ('idformula', models.AutoField(primary_key=True, serialize=False)),
                ('formulaname', models.CharField(max_length=50, verbose_name='Nombre de la formula')),
                ('variables', models.JSONField(blank=True, null=True, verbose_name='Variables')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
