# Generated by Django 5.1.1 on 2024-10-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='diet',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='diet',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='diet',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
