# Generated by Django 5.1.1 on 2024-10-18 05:59

from django.db import migrations, models

def create_formulas(apps, schema_editor):
    Formula = apps.get_model('formulas', 'Formula')

    # Crear la fórmula Harris-Benedict con ID 1
    Formula.objects.create(idformula=1, formulatype='Harris')

    # Crear la fórmula Mifflin-St Jeor con ID 2
    Formula.objects.create(idformula=2, formulatype='Mifflin')


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulas',
            name='formulaname',
        ),
        migrations.RemoveField(
            model_name='formulas',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='formulas',
            name='variables',
        ),
        migrations.AddField(
            model_name='formulas',
            name='formulatype',
            field=models.CharField(choices=[('harris', 'Harris-Benedict'), ('mifflin', 'Mifflin-St Jeor')], default='harris', max_length=50, verbose_name='Tipo de formula'),
        ),
    ]