# Generated by Django 5.1.1 on 2024-10-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_remove_formulas_formulaname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formulas',
        ),
    ]
