# Generated by Django 5.1.1 on 2024-10-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_delete_formulas'),
        ('nutrition', '0003_diet_user'),
    ]

    operations = [
    ]
